# Generated by Django 3.0.6 on 2020-05-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200525_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='duedate',
            field=models.DateTimeField(null=True),
        ),
    ]
